# config/gateway.config.yml

# http
http:
  port: 8080

# apiEndpoints
apiEndpoints:
  user:
    host: localhost
    paths: "/v1/user/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

  product:
    host: localhost
    paths: "/v1/product/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

# serviceEndpoints
serviceEndpoints:
  userService:
    url: "http://localhost:7005/"

  productService:
    url: "http://localhost:8005/"

# policies
policies:
  - cors
  - log
  - proxy

# pipelines
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,PUT,PATCH,POST,DELETE"
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true

  productPipeline:
    apiEndpoints:
      - product
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,PUT,PATCH,POST,DELETE"
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
